### PR TITLE
How to use jsonapi.org format in sails.js?

### PR DESCRIPTION
**Pull request by JemiloII**
Tutorial on how to use the jsonapi.org format in Sails.js. This is useful for integrating sails.js with frameworks like ember.js which rely heavily on the jsonapi.org json format,

### CODE REVIEW

**Comment by listepo** [comment]
can the new version better add support in core for jsonapi?
jsonapi: true

**Comment by RWOverdijk** [comment]
:+1:

**Comment by yedhukrishnan** [comment]
@JemiloII Can you please push the code to the repo? :)

**Comment by JemiloII** [comment]
Sure, I'll get to it after work~

**Comment by JemiloII** [comment]
Alright, everything is posted to here: https://github.com/sails101/using-the-jsonapi-format

**Comment by ghost** [comment]
Yay! I'll try it out in my app. Thanks.

**Comment by listepo** [comment]
@nahtnam, see https://github.com/mphasize/sails-generate-ember-blueprints

**Comment by ghost** [comment]
@listepo It doesn't support embedded json. :(

I'll probably end up using either that or the ember adapter. Not sure yet...

EDIT: Whoops, just deleted my reply (after this), wrong thread.

**Comment by nahtnam** [comment]
@listepo I am starting to understand sails more and more. I really appreciate this PR!

**Pull request closed without merging**
